### ISSUE TITLE
Boost version

### ISSUE THREAD

**Issue by corna** [MarekPikula/xournalpp#9]
The minimum required version for boost in configure.ac is 1.54, a very recent boost version. This can be a problems in systems like Debian Wheezy (stable), where the latest boost version is [1.49](https://packages.debian.org/wheezy/libboost-filesystem-dev), or Ubuntu Precise (12.04 LTS), where the latest boost version is [1.48](http://packages.ubuntu.com/precise/libboost-filesystem-dev). Which is the real minimum required version?

**Comment by MarekPikula** [comment]
Wow... For me it's unimaginable how old those packages are... 1.48 is back from 15.11.2011 (it's even older than our current poppler), but thanks for pointing out.
I chose 1.54, because it introduced Boost.Log library, which I was wondering to use to unify logging in future. For now boost 1.48 is minimum version, because it's first one with Boost.Locale library. Since then it was updated 3 times, so I don't guarantee, that everything will work properly. Also Boost.Filesystem was updated 3 times and Boost.Iostreams twice.
If we still want to use boost (and I beg you so) and want to support those systems, we'd have to enable user to compile Xournal++ with something like --build-boost flag. It needs some autoconf magic, which I don't think I'm capable of for now, but it's possible to make.
Anyways I woudn't take care of it, because I'm not too familiar with Debian environment, so it'd need someone to maintain.

**Comment by corna** [comment]
I know, it's awfully old, but lots of people use Ubuntu LTS or Debian Stable...
The boost.m4 macro has already support for an external boost library (--with-boost=DIR), and the user can link it statically with --enable-static-boost, so an user with a old distro release can simply download the latest boost version from the boost website and build xournalpp with that boost linked statically
I'll test it later if it works

**Comment by MarekPikula** [comment]
Ok. If it'll work, please write instruction in README.

**Comment by MarekPikula** [comment]
I forgot about this issue. It was implemented a while ago, so I'm closing it.
